name: HeroesSinLimite
favicon: null
layout_spectrum: 1
typography_spectrum: 0.6004
title: Héroes Sin Límite
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#121818'
    - '#82a3ac'
    - '#feecde'
    - '#465a5b'
    - '#d62027'
  brandStrength: 0.25
  lightness: 0
  saturation: 0.8125
  rhythmicContrast: 1
purpose: []
