name: HeroesSinLimite
favicon: null
layout_spectrum: 0.31213
typography_spectrum: 0.52333
title: Héroes Sin Límite
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#121818'
    - '#82a3ac'
    - '#feecde'
    - '#465a5b'
    - '#d62027'
  brandStrength: 0.125
  lightness: 0.8125
  saturation: 0.375
  rhythmicContrast: 0.75
purpose: []
