typography_spectrum: 0.021568729309365153
color:
  brandColors:
    - '#1C1D21'
    - '#31353D'
    - '#445878'
    - '#92CDCF'
    - '#EEEFF7'
  brandStrength: 0.7603592628147453
  lightness: 0.0345493087079376
  saturation: 0.07174552674405277
  rhythmicContrast: 0.32967944093979895
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.37246717931702733
analytics:
  google: UA-77397683-1
  facebook: null
  twitter: null
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/f8f27a8b-22b5-4ad0-8122-b03d79f2f7f5.png
name: Heroes sin Limite
cta:
  domain: null
  bucket: null
  version: null
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/b3bd52aa-caa7-40fe-a1bd-2b5ba000570d.jpg
title: Héroes sin límite
description: Donde el cine y los cómics se unen
purpose: []
