name: Heroes sin Limite
favicon: null
layout_spectrum: 0.36417
typography_spectrum: 0.53104
title: Héroes sin Límite
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-77397683-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#181818'
    - '#ffffff'
    - '#ed1d25'
    - '#b7b5b6'
    - '#93302a'
  brandStrength: 0
  lightness: 0.5
  saturation: 0
  rhythmicContrast: 1
purpose: []
