name: HeroesSinLimite
favicon: null
layout_spectrum: 0.04246025811880827
typography_spectrum: 0.5059842301998287
title: Héroes Sin Límite
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#191919'
    - '#fefefe'
    - '#ec1d24'
    - '#969595'
    - '#555454'
  brandStrength: 0.8571412221062928
  lightness: 0.22839606180787086
  saturation: 0.17160941590555012
  rhythmicContrast: 0.017011210089549422
purpose: []
