name: Heroes sin Limite
favicon: null
layout_spectrum: 0.62814
typography_spectrum: 0.53297
title: Héroes sin Límite
description: Todo sobre Comics y el Cine
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-77397683-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#181818'
    - '#ffffff'
    - '#ed1d25'
    - '#b7b5b6'
    - '#93302a'
  brandStrength: 0.4375
  lightness: 0
  saturation: 0.75
  rhythmicContrast: 0.5
purpose: []
