name: HeroesSinLimite
favicon: null
layout_spectrum: 0.26789
typography_spectrum: 0.52333
title: Héroes Sin Límite
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#191919'
    - '#fefefe'
    - '#ec1d24'
    - '#969595'
    - '#555454'
  brandStrength: 0.75
  lightness: 0.0625
  saturation: 0.6875
  rhythmicContrast: 0.75
purpose: []
