name: HeroesSinLimite
favicon: null
layout_spectrum: 0.12524
typography_spectrum: 0.53104
title: Héroes Sin Límite
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#181818'
    - '#ffffff'
    - '#ed1d25'
    - '#b7b5b6'
    - '#93302a'
  brandStrength: 0.125
  lightness: 0
  saturation: 1
  rhythmicContrast: 0.25
purpose: []
